# Generated by Django 5.0.7 on 2024-07-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CantonesePhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('text', models.CharField(max_length=255)),
                ('mp3_file', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FrenchPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('text', models.CharField(max_length=255)),
                ('mp3_file', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GermanPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('text', models.CharField(max_length=255)),
                ('mp3_file', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GreekPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('text', models.CharField(max_length=255)),
                ('mp3_file', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HebrewPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('text', models.CharField(max_length=255)),
                ('mp3_file', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HungarianPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('text', models.CharField(max_length=255)),
                ('mp3_file', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JapanesePhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('text', models.CharField(max_length=255)),
                ('mp3_file', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MandarinPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('text', models.CharField(max_length=255)),
                ('mp3_file', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RomanianPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('text', models.CharField(max_length=255)),
                ('mp3_file', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RussianPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('text', models.CharField(max_length=255)),
                ('mp3_file', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UkranianPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('text', models.CharField(max_length=255)),
                ('mp3_file', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='player',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
