# Generated by Django 5.0.7 on 2024-07-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cantonesephrase_frenchphrase_germanphrase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='guessHintNum',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='game',
            name='player',
            field=models.CharField(default='', max_length=50),
        ),
    ]
