# Generated by Django 5.0.7 on 2024-08-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_game_guesshintnum_alter_game_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='lang',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='phrase',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='phraseSound',
            field=models.CharField(default='', max_length=100),
        ),
    ]
