# Generated by Django 5.0.7 on 2024-08-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_game_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameStatus',
            field=models.IntegerField(default=1),
        ),
    ]
