# Generated by Django 5.0.7 on 2024-08-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_game_gamestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='createdAt',
            field=models.DateTimeField(),
        ),
    ]
